= Lab 6 - Pushing .NET Core Apps to Pivotal Cloud Foundry

== Target

. If you haven't already, download the latest release of the Cloud Foundry CLI from https://github.com/cloudfoundry/cli/releases for your operating system and install it.

. Set the API target for the CLI: (set appropriate end point for your environment)
+
----
$ cf api https://api.run.pivotal.io
----

. Login to Pivotal Cloud Foundry:
+
----
$ cf login
----
+
Follow the prompts

== Push It!

The tutorial application has been built for you and is ready to deploy.

. Change to the _lab7_ directory and unzip the _simple-todos_ archive:
+
----
$ cd $BOOTCAMP_HOME/labs/lab7
$ unzip aspnet-core-helloworld-master.zip
----

. View the application manifest, then push the app.
+
----
$ cd aspnet-core-helloworld-master
$ cat manifest.yml
$ cf push
----

== Interact with App from CF CLI

. Get information about the currently deployed application using CLI apps command:
+
----
$ cf apps
----
+
Note the application name for next steps

. Get information about running instances, memory, CPU, and other statistics using CLI instances command
+
----
$ cf app <<app_name>>
----

. Stop the deployed application using the CLI
+
----
$ cf stop <<app_name>>
----

. Delete the deployed application using the CLI
+
----
$ cf delete <<app_name>>
----
